### ISSUE TITLE
[Errno 32] Broken pipe - To much meta data ?

### ISSUE THREAD

**Issue by gateway** [Kosinkadink/ComfyUI-VideoHelperSuite#56] opened 2023-11-04 02:11 UTC
Not sure why im getting this now, I updated today everything and now when saving on VHS Combine it throws out this error.

Error occurred when executing VHS_VideoCombine:

```
[Errno 32] Broken pipe

File "E:\Stable-Diffusion\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\Stable-Diffusion\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\Stable-Diffusion\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 209, in combine_video
self.save_with_tempfile(args, metadata_args[1], file_path, frames, env, crf)
File "E:\Stable-Diffusion\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 90, in save_with_tempfile
proc.stdin.write(frame.tobytes()) 
```

**Comment by AustinMroz** [comment] 2023-11-04 02:25
Metadata wasn't among the changes that was made today, so I have my doubts that it would be related. I'll probably look into lowering the severity of the metadata warning since I've not seen any actual issues caused by it.

The error message provided tells me that the ffmpeg process closed with some error, but doesn't go far enough back to give me any insight on what the issue is. Can you provide earlier logs?

**Comment by gateway** [comment] 2023-11-04 02:29
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/519563/bcdba2d1-f281-4a9a-a339-1f146a1034dc)

**Comment by gateway** [comment] 2023-11-04 02:34
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/519563/0e99cfdc-d1b8-498f-8c18-d027a4df693c)
full stack

**Comment by AustinMroz** [comment] 2023-11-04 02:36
Thanks, I'm looking into it. Can you check if it breaks with other video formats selected?

**Comment by gateway** [comment] 2023-11-04 02:48
Its something with my workflow I created because other workflows work.. i have no idea.. i ripped everything out.. I can post the workflow also.. I could be an idiot and doing something wrong. lol :)

![workflow](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/519563/0cd2ed09-3430-4f87-aa2e-8e46cf8e0e1e)

**Comment by AustinMroz** [comment] 2023-11-04 02:52
I've found the issue and I'll push the fix in the next couple minutes once I've done my sanity checks.

As you guessed initially, when it saves with longer metadata, it uses a different code path. While the logic related to metadata isn't at issue here, the crf information gets added a second time in the command where it shouldn't.

**Comment by gateway** [comment] 2023-11-04 02:55
Is their a way to opt out of meta data if you dont want to add it, im assuming your adding the workflow..

**Comment by AustinMroz** [comment] 2023-11-04 02:59
Not currently, but there was an earlier issue asking about it as well. I'll look into adding it in the future.

**Comment by Kosinkadink** [comment] 2023-11-29 07:55
A recent PR makes the Broken pipe due to metadata no longer causs everything to break down, and simply retries without the metadata. A save_metadata toggle is also present. Closing the issue, since should have been fixed for a several days now 👍

**Closed by Kosinkadink** 2023-11-29 07:55 UTC
