### ISSUE TITLE
[Bug] Right-click on VHS Video Combine not working

### ISSUE THREAD

**Issue by GentlemanHu** [Kosinkadink/ComfyUI-VideoHelperSuite#93] opened 2023-12-24 09:27 UTC
![2023-12-24 17 25 34](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/34559079/8bda1b09-8af7-4bb0-9a70-cb6aedf7120d)

**Comment by GentlemanHu** [comment] 2023-12-24 09:28
ComfyUI version : https://github.com/comfyanonymous/ComfyUI/commit/a252963f956a7d76344e3f0ce24b1047480a25af

**Comment by AustinMroz** [comment] 2023-12-24 17:23
I know from development that this issue occurs when the code that adds options to the menu throws an error, but I've not had any luck with reproducing or guessing at what the current bug might be.

If you open the developer tools -> console, there should be an error message that is produced on right click.

**Comment by iamaguai** [comment] 2023-12-25 02:08
comfyui-share-common.js:90 Uncaught TypeError: Cannot read properties of undefined (reading 'format')
    at getPotentialOutputsAndOutputNodes (comfyui-share-common.js:90:25)
    at node.getExtraMenuOptions (comfyui-manager.js:1039:35)
    at LGraphCanvas.getNodeMenuOptions (litegraph.core.js:13208:30)
    at LGraphCanvas.getNodeMenuOptions (ui_mixlab.js:547:42)
    at LGraphCanvas.getNodeMenuOptions (groupNode.js:1139:38)
    at LGraphCanvas.processContextMenu (litegraph.core.js:13330:34)
    at LGraphCanvas.processMouseDown (litegraph.core.js:6295:10)
    at LGraphCanvas.processMouseDown (undoRedo.js:144:29)
    at LGraphCanvas.processMouseDown (app.js:882:37)

**Comment by AustinMroz** [comment] 2023-12-25 03:08
The issue appears to be with ComyUI-Manager. It has code specific to our VideoCombine node to try and extract animated images for their "Share Output" button, but that code fails to properly handle the case where a preview doesn't exist yet (the node was just added)

**Comment by iamaguai** [comment] 2023-12-25 04:37
> The issue appears to be with ComyUI-Manager. It has code specific to our VideoCombine node to try and extract animated images for their "Share Output" button, but that code fails to properly handle the case where a preview doesn't exist yet (the node was just added)

you are right. when i set share :none at manager menu, i create a new VideoCombine, this issue appears.

**Comment by Kosinkadink** [comment] 2023-12-26 21:02
Looks like the fix has been merged into the ComfyUI-Manager - I will close the issue for now, but if it still happens for you after updating ComfyUI-Manager, reopen the issue.

**Closed by Kosinkadink** 2023-12-26 21:02 UTC
