### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by curlysasha** [Kosinkadink/ComfyUI-VideoHelperSuite#29] opened 2023-10-20 14:10 UTC
new video upload node
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/116119767/331b814e-7cc5-4270-8abe-dff57bd0470e)

upload path working ok
video combine node not playing video after generation

**Comment by Kosinkadink** [comment] 2023-10-20 14:34
If you update to most recent version, Video Combine node should play video, and old workflows that used Load Video (Upload) node should no longer have unrecognized nodes. It was not intended to be a 'new' node. A PR I merged in earlier broke a bunch of stuff I thought they had tested for, so I am now fixing stuff. I will also revert the upload directory to input by default, so that old workflows will work.

I will look into why upload node is not accepting mov. Thanks for the report!

**Comment by curlysasha** [comment] 2023-10-20 14:37
> If you update to most recent version, Video Combine node should play video, and old workflows that used Load Video (Upload) node should no longer have unrecognized nodes. It was not intended to be a 'new' node. A PR I merged in earlier broke a bunch of stuff I thought they had tested for, so I am now fixing stuff. I will also revert the upload directory to input by default, so that old workflows will work.
> 
> I will look into why upload node is not accepting mov. Thanks for the report!

thanks to you!

**Comment by Kosinkadink** [comment] 2023-10-20 15:08
@JaredTherriault Hey, wanted to give some feedback on your PR now that it's merged in:

It broke almost all core functionality, from Load Video (Upload) node not having the right ID, to Load Video (Upload) node no longer working at all because it does not append the full path of a video and instead tries to put in just the local directory. Video playback broke, the frame_count output was 1) not the actual count but the original count, and 2) was a float instead of an int as the value returned by OpenCV from the const is a float. The fact that input (without VHS_upload subdirectory) is not an option also breaks all previous workflows.

I mean this as constructive criticism btw - be sure that on any subsequent PRs you make, you don't introduce code regressions by testing workflows made from before your changes with the changes to prevent stuff like this! I do appreciate the PR in general. Some of these bugs, however, seem like they were introduced because they were not tested at all.

**Comment by aleksej622** [comment] 2023-10-20 15:22
I also have some trouble with the video upload node. Video path works more or less

**Comment by Kosinkadink** [comment] 2023-10-20 15:24
^ That Load Video (Upload) issue will soon be fixed, i need to revert it to properly use the absolute path. Should be out in 10 minutes!

**Comment by Kosinkadink** [comment] 2023-10-20 15:34
Ok, should be fixed now with most recent commit! Let me know if it works.

**Comment by dkamajix** [comment] 2023-10-20 16:08
thank you for that, and all you do! that worked!

**Comment by Kosinkadink** [comment] 2023-10-20 16:09
Np, let me know if you find anything else potentially broken, might be more bugs hiding in there!

**Comment by dkamajix** [comment] 2023-10-20 18:20
actually getting another issue here:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/e802bc3a-7850-46de-a29d-3b530e7f3bf3)

Prompt outputs failed validation
VHS_LoadVideo:
- Failed to convert an input value to a FLOAT value: desired_frame_rate, None, float() argument must be a string or a real number, not 'NoneType'
- Failed to convert an input value to a INT value: select_every_nth, None, int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by Kosinkadink** [comment] 2023-10-20 18:31
@dkamajix if you delete that node and replace it, do you still get the error?

**Comment by InB4DevOps** [comment] 2023-10-20 19:19
> @dkamajix if you delete that node and replace it, do you still get the error?

did that and it works again. thanks

**Comment by AustinMroz** [comment] 2023-10-20 20:37
My impression from looking things over is that most changes are individually good and that it's better to keep the pull request with any needed changes.

Currently, load_video_pil is called iff an error occurs when loading with opencv fails. I can only guess this was done in an attempt to extract timing information from animated gifs, but it greatly obfuscates error information when opencv fails to load a video file that PIL will never be able to load. Instead, I would suggest that `load_video` calls `load_video_cv` or `load_video_PIL`  based off the existing but unused `is_video`.

The change to use an `upload_to_directory` is positive, but caused some confusion for me. I think it would be cleaner to reorder this to be after the file upload button, have it be added on the js side (like the button itself), and not be serialized, but changing this would require people re-add nodes.

`video` paths have doubled forward slashes for me. I'm currently unsure what is causing it, since the offending code doesn't appear to be changed from when I initially wrote it, but I'm looking into it.

Seperate of these issues, users needing to remove and re-add nodes on update isn't great and seems to be the single most frequent source of issues. I'll do some tinkering to see if this process can be automated.

**Comment by JaredTherriault** [comment] 2023-10-20 21:48
> @JaredTherriault Hey, wanted to give some feedback on your PR now that it's merged in:
> 
> It broke almost all core functionality, from Load Video (Upload) node not having the right ID, to Load Video (Upload) node no longer working at all because it does not append the full path of a video and instead tries to put in just the local directory. Video playback broke, the frame_count output was 1) not the actual count but the original count, and 2) was a float instead of an int as the value returned by OpenCV from the const is a float, causing all workflows that used it to initialize Empty Latent Image to break. The fact that input (without VHS_upload subdirectory) is not an option also breaks all previous workflows.
> 
> I mean this as constructive criticism btw - be sure that on any subsequent PRs you make, you don't introduce code regressions by testing workflows made from before your changes with the changes to prevent stuff like this! I do appreciate the PR in general. Most of these bugs, however, seem like they were introduced because they were not tested at all.

I don't upload PRs that I don't test. Try replacing the nodes. Sorry for the inconvenience. I did not intend to give you more work, I only meant to contribute. I'll just keep these as separate nodes in another repo, feel free to revert the change.

**Comment by Kosinkadink** [comment] 2023-10-21 00:36
@JaredTherriault the replacing node thing is luckily only to do with that one node likely due to the upload_to_directory var being added to the middle (we can likely move it to the end and it will fix it), so no worries! I should have more closely examined the PR and gave more feedback. I apologize for the unnecessary rudeness on my part. I was low on sleep and the whiplash of discovering the issues after thinking the PR was working fine clouded my judgement haha. I should have just immediately reverted the changes and restored the PR when I noticed the problems instead of hodge-podging fixes left and right for stuff as I discovered them.

Definitely feel free to keep contributing, I appreciate the contribution! I'll do a better job looking through the PRs moving forward and providing feedback 👍 .

**Comment by Kosinkadink** [comment] 2023-10-21 00:39
@AustinMroz 

The double quotes are due to one of my hasty fixes to not require a subdirectory for video path - in the Upload Video class code, I made the subdirectory string empty so that raw 'input' directory can be used again, but the rest of the code that uses expects a string to be there, so it keeps the slash before and after the empty string, thus resulting in the double slash. We can add code that checks if subdirectory is empty and not add one of the slashes (or changing the logic a little bit to do it automatically).

**Comment by JaredTherriault** [comment] 2023-10-21 01:57
> @JaredTherriault the replacing node thing is luckily only to do with that one node likely due to the upload_to_directory var being added to the middle (we can likely move it to the end and it will fix it), so no worries! I should have more closely examined the PR and gave more feedback. I apologize for the unnecessary rudeness on my part. I was low on sleep and the whiplash of discovering the issues after thinking the PR was working fine clouded my judgement haha. I should have just immediately reverted the changes and restored the PR when I noticed the problems instead of hodge-podging fixes left and right for stuff as I discovered them.
> 
> Definitely feel free to keep contributing, I appreciate the contribution! I'll do a better job looking through the PRs moving forward and providing feedback 👍 .

No, I've pretty much learned my lesson not to contribute anymore. Thanks.

**Comment by Kosinkadink** [comment] 2023-10-21 02:11
@JaredTherriault hey, I think your PR has very solid ideas, and it was my responsibility to vet that things went smoothly in the PR process and I failed to follow through on that. Outside of that, we all have a goof with submitted code at some point, so definitely don't feel disenchanted by that! I once made a commit at a startup I worked for years ago that accidentally slammed every single commit in history with every single tag that existed.

I should have been more productive in my initial message to you about the PR feedback in this thread. Contributions big and small are important to keep projects like this alive, and at the end of the day it is on me for the issues that came up as a result of me merging the PR and not you.

**Comment by JaredTherriault** [comment] 2023-10-21 03:00
> @JaredTherriault hey, I think your PR has very solid ideas, and it was my responsibility to vet that things went smoothly in the PR process and I failed to follow through on that. Outside of that, we all have a goof with submitted code at some point, so definitely don't feel disenchanted by that! I once made a commit at a startup I worked for years ago that accidentally slammed every single commit in history with every single tag that existed.
> 
> I should have been more productive in my initial message to you about the PR feedback in this thread. Contributions big and small are important to keep projects like this alive, and at the end of the day it is on me for the issues that came up as a result of me merging the PR and not you.

I'm not bothered by feedback. That is how collaborative efforts work. Together, we get it right.

What I'm not down with is how you went behind my back to put me on blast in the discord channel because you thought I wasn't looking.

Imagine joining a community, and enjoying being a part of it so much that you want to give back to it. You spend your whole weekend learning how comfy nodes and the js frontend work so you can build something that the community will appreciate. I was so excited to see you say "thanks for your contribution, this will be very helpful." I got that, yeah. But then I got more than I bargained for when you called me a "neanderthal" and said that I "fucked" you among other choice words. 

I really looked up to you man, I saw you as someone to emulate because when it comes to code you crush it but dude, you broke me. I met my hero today, and I will never be able to look at you the same way again.

**Comment by Kosinkadink** [comment] 2023-10-21 04:45
Jared and I hashed out the issue via discord, so removed comment to bury the hatchet.

The code should be in a good state now, let me know if any of you experience any more oddities in the Upload Video (Upload/Path) nodes. I will soon add back Jared's PIL fallback code for specifically apng, webp, and mjpeg, so those formats will be supported soon thanks to @JaredTherriault 's contribution.

**Comment by dkamajix** [comment] 2023-10-21 04:56
Thank you both!Will try in my am. DSent from my iPhoneOn Oct 21, 2023, at 12:46 AM, Jedrzej Kosinski ***@***.***> wrote:﻿
Jared and I hashed out the issue via discord, so removed comment to bury the hatchet.
The code should be in a good state now, let me know if any of you experience any more oddities in the Upload Video (Upload/Path) nodes. I will soon add back Jared's PIL fallback code for specifically apng, webp, and mjpeg, so those formats will be supported soon thanks to @JaredTherriault 's contribution.

**Comment by dkamajix** [comment] 2023-10-21 13:51
Hi, I seem to still have the issue with VHS video loader
I can see that now when I click to upload or drag and drop, last nights directory prefix it was adding is now gone.
now it says input/name of file.
but they error out. 
but I believe it should say input//name of file for it to work.
take a look at the pic for ref. the ones with double slash load.. the ones with one slash dont.
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/eb6305df-370f-4c2a-b790-25a01b8aa75c)

here is the error again:
Prompt outputs failed validation
VHS_LoadVideo:
- Custom validation failed for node: video - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4
- Custom validation failed for node: upload_to_directory - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4
- Custom validation failed for node: desired_frame_rate - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4
- Custom validation failed for node: force_size - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4
- Custom validation failed for node: frame_load_cap - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4
- Custom validation failed for node: skip_first_frames - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4
- Custom validation failed for node: select_every_nth - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\input/LIVINGROOM_GIRL DANCE_576x1024.mp4

**Comment by curlysasha** [comment] 2023-10-21 16:27
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/116119767/6dd6feab-770d-4945-b6a7-13c80c5c5df3)

Path load video have VERY huge ram usage. and i have ram problem in generation last night
this starts from yesterday update

**Comment by Kosinkadink** [comment] 2023-10-21 16:31
Gotcha, for the time being I am going to revert changes back to how they were prior to the update, and then will drip the changes back piece by piece during the week. I'll let you know when the code is reverted, so you can test it again!

**Comment by Kosinkadink** [comment] 2023-10-21 17:27
The code should now be reverted - if you pull latest changes, hopefully everything will work exactly as it did before. I will add back parts of the code i reverted in pieces, but things should be back to stable now!

**Closed** 2023-10-23 10:23 UTC
