### ISSUE TITLE
Video loader external path loading...

### ISSUE THREAD

**Issue by rocky533** [Kosinkadink/ComfyUI-VideoHelperSuite#279] opened 2024-08-20 23:41 UTC
Why oh why does the video loader break when you try to use a custom video path via combining strings.

If i choose the video in the loader, it loads once then will not load it again.  This works perfect, and also works perfect when set video to input and double click on the video input to get a single line string node and put the path there.

However
If i change video to input, send it the path via joining strings to get the path, (i want to load many videos with same path and different files) it will load the video fine.. than when i press q again.  It will load it again.... restarting the workflow when everything depends on this load... Its loading the same thing as if it is new... In a large complex workflow like mine it will restart and redo the entire video again... when it should not redo anything it just did, and only do the added things i enabled like an upscale pass.  Currently it redoes the base again...

This happens 2 times when using video as an input that is joined strings.  After 2 loads the second time it caches everything properly and does not reload that video unless i change something in the loader settings.  This forces you to load the video 2 times before you do anything with it or it will restart a flow that requires it.

Is this a bug?  Can i send the video loader a path that is made by combining many string textboxes and not have it restart the workflow.  I know it works, and assume this is a bug.  Can i do anything to get around this because many of my workflows break in this way.

**Comment by AustinMroz** [comment] 2024-08-21 00:42
The 4-5 times similar issues have come up with node caching before, it has consistantly been an bug in the IS_CHANGED method of another node outside VHS. As of August 16th, ComfyUI no longer swallows these error messages, so if you've updated very recently, there will probably be an error message in the console that describes what is going wrong.

**Comment by rocky533** [comment] 2024-08-21 02:06
do you know what other node causes this so i can avoid it? Is it the combine method used?  I figured it was since it works without combining perfect.

Is there any node you can point me to to allow me to combine strings into something compatible with VHS video input?
If not is there any way i can interact with the text box generated when i double click on the video input?  I cant connect it to anything but that video input, so i cant extract parts to avoid users needing to retype things.  

Thanks for the quick response.

**Comment by AustinMroz** [comment] 2024-08-21 02:32
Possibly, but I would need to run the workflow myself to make sure. I know one of the times I dug into this it was a string input node that was bugged. Though it caching properly after a couple runs is unusual and not something I've seen before

**Comment by rocky533** [comment] 2024-08-21 02:36
My latest beta has this issue, i am positive its been there all along, in all versions.  I have tried 4 different string combine nodes to no avail.  

https://civitai.com/models/271305/video-to-video-workflows

Like i said the node that is generated when i double click on the video input, is... different.  I cant do anything with it besides connect it to the input.  It wont connect to any string input of any other node despite being a string.

**Comment by AustinMroz** [comment] 2024-08-21 16:42
I was able to reproduce and I can confirm none of the other nodes are at fault. The recent execution changes to ComfyUI have changed what information is passed to the `IS_CHANGED` in a way that makes a solution here quite inconvenient.

I've reached out to see if this is something that needs to be fixed on the ComfyUI side.

**Comment by rocky533** [comment] 2024-08-21 18:40
I assume this change is also why none of my display info boxes populate anymore.   :(

TBH this new comfy is good, just new and buggy, i really like the cancel button now.. animate diff does not need to wait until finished rendering a step to cancel a render making starting stopping easier.

**Comment by Kosinkadink** [comment] 2024-08-21 20:58
FYI AnimateDiff not needing to wait a step to cancel isn't due to ComfuUI update, instead I found the function recently that ComfyUI uses to check if a workflow has been cancelled that it calls every step, so I started calling it before each context window is ran.

**Comment by rocky533** [comment] 2024-08-21 23:48
Now that i did not know, thanks for your work :)

**Comment by AustinMroz** [comment] 2024-08-22 02:58
There's now an pull request to ComfyUI to fix the issue.

Resolved by comfyanonymous/ComfyUI#4535

**Closed** 2024-08-22 03:48 UTC

**Comment by rocky533** [comment] 2024-08-27 21:18
Wanted to thank you for this, i honestly thought i was doing something wrong.
